# 排序(Sorting)算法 

<image src='./images/sort_method.jpg', style='zoom:50%'/>

In [50]:
import numpy as np

<img src='images/sort_method.jpg', style="100%">

## 1. 插入排序 

### 1.1 直接插入排序 

插入排序(insertion sorting)：假设前面的元素已经排好序，将这个元素插入前面的元素，为提高速度，可采用二分查找来插入．

In [49]:
# normal insertion sort algorithm
def insertion_sort(lst):
    
    for idx in range(1, len(lst)):
        current_value = lst[idx]
        position = idx
        while position > 0 and lst[position-1] > current_value:
            lst[position] = lst[position-1]
            position -=1
        lst[position] = current_value
# insertion sort with binary search    
def insertion_sort_binary_search(lst):   
    for idx in range(1, len(lst)):
        current_value = lst[idx]
        position = idx
        lower = 0
        higher = position - 1
        while higher >= lower:
            mid = (higher + lower) / 2
            if lst[mid] > current_value:
                higher = mid -1
            else:
                lower = mid + 1
#             print lower
#             print higher
        while position > lower:
            lst[position] = lst[position-1]
            position -=1
        lst[position] = current_value
#         print lst

复杂度的问题：

算法最坏复杂度为$O(n^2)$,最好为$O(n)$

### 1.2 希尔排序

## 2. 选择排序

## 3.交换排序

### ３.1 冒泡排序 

算法：

+ １．比较相邻的元素，若第一大于第二，就交换他们
+ ２．对每一对相邻元素进行相同操作，使最大元素到最后．
+ ３．除却后部排好序的元素，然后再次进行１，２步操作


复杂度：

$$(n-1) + (n-2) + ...+2 + 1 = \frac{n(n-1)}{2} = O(n^2)$$

In [9]:
def bubblesort(numbers):
    for i in range(len(numbers)-1):
        for j in range(len(numbers)-i-1):
            if numbers[j] > numbers[j+1]:
                numbers[j], numbers[j+1] = numbers[j+1], numbers[j]
    return numbers

In [10]:
import numpy as np
nums = np.random.randint(100, size=10)
nums

array([56, 93, 95, 73,  6, 75, 96,  5, 39, 98])

In [11]:
print(bubblesort(nums))

[ 5  6 39 56 73 75 93 95 96 98]


### 3.2 快速排序

+ 1. 选择最后一个元素作为基准
+ 2. 之前所有元素和基准元素比较，分为两部分
+ 3. 对每部分进行１，２操作

复杂度：


In [96]:
def partition(arr, firstIndex, lastIndex):
    i = firstIndex - 1
    for j in range(firstIndex, lastIndex):
        if arr[j] <= arr[lastIndex]:
            i += 1
            arr[j], arr[i] = arr[i], arr[j]
#             print 'j is ' + str(j)
#             print arr
    arr[i+1], arr[lastIndex] = arr[lastIndex], arr[i+1]
    return i


def QuickSort(arr, firstIndex, lastIndex):
    if firstIndex < lastIndex:
        divIndex = partition(arr, firstIndex, lastIndex)
        QuickSort(arr, firstIndex, divIndex)
        QuickSort(arr, divIndex+1, lastIndex)
    else:
        return

In [97]:
arr = np.random.randint(1000, size=10)
print arr
QuickSort(arr, 0, len(arr)-1)
print arr

[908 144 713  41 910 998 159 385  54 650]
[ 41  54 144 159 385 650 713 908 910 998]


In [87]:
# arr = np.random.randint(100, size=5)
arr = [75, 31, 96, 50, 76]

In [88]:
arr

[75, 31, 96, 50, 76]

In [89]:
partition(arr, 0, len(arr)-1)

j is 0
[75, 31, 96, 50, 76]
j is 1
[75, 31, 96, 50, 76]
j is 3
[75, 31, 50, 96, 76]


2

In [98]:
partition(arr, 0, len(arr)-1)
arr

# 推演
# partition(a, 0, 4):
#     i=-1
#     j = 0
#         a[0] <=a[4]
#             i = 0
#             a[0], a[0] = a[0], a[0]
#     j = 1
#         a[1] <= a[4]
#             i = 1
#             a[1], a[1] = a[1], a[1]
#     j = 2
#         a[2] > a[4]
#     j = 3
#         a[3] <= a[4]
#             i = 2
#             a[2], a[3] = a[3], a[2]
#     a[4], a[2] = a[2], a[4]
#     return 2

array([ 41,  54, 144, 159, 385, 650, 713, 908, 910, 998])

快速排序算法平均复杂度为$nlog(n)$

### 合并排序

合并排序(merge sort):　二路排序，将原始数据分为两部分，分别进行排序，然后将各自集合并． 典型分治法测略．

+ Split 
+ Merge

时间复杂度：

Split 二分log(n)； Merge 每个元素都会被放入排序好的list中,每个需要ｎ步．

所以总的复杂度为$O(nlogn)$


<img src='images/merg_sort.png', style='100%'>

# ???? 复杂度不太懂啊

In [4]:
def merge_sort(lst):
    print 'Spliting: ' + str(lst)
    
    #spliting lst
    if len(lst) > 1:
        mid = len(lst) // 2
        left_half = lst[:mid]
        right_half = lst[mid:]
        merge_sort(left_half)
        merge_sort(right_half)

        # index of left_half, right_half & lst
        i = 0
        j = 0
        k = 0

        # while until one of the list has been iterated
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                lst[k] = left_half[i]
                i += 1
            else:
                lst[k] = right_half[j]
                j += 1
            k += 1

        # To iterate the rest one
        while i < len(left_half):
            lst[k] = left_half[i]
            i += 1
            k += 1
        while j < len(right_half):
            lst[k] = right_half[j]
            j += 1
            k += 1
        print 'Merging: ' + str(lst)
    

In [6]:
lst = [54, 26, 93, 17, 77, 31, 44, 55, 20]
merge_sort(lst)
print(lst)

Spliting: [54, 26, 93, 17, 77, 31, 44, 55, 20]
Spliting: [54, 26, 93, 17]
Spliting: [54, 26]
Spliting: [54]
Spliting: [26]
Merging: [26, 54]
Spliting: [93, 17]
Spliting: [93]
Spliting: [17]
Merging: [17, 93]
Merging: [17, 26, 54, 93]
Spliting: [77, 31, 44, 55, 20]
Spliting: [77, 31]
Spliting: [77]
Spliting: [31]
Merging: [31, 77]
Spliting: [44, 55, 20]
Spliting: [44]
Spliting: [55, 20]
Spliting: [55]
Spliting: [20]
Merging: [20, 55]
Merging: [20, 44, 55]
Merging: [20, 31, 44, 55, 77]
Merging: [17, 20, 26, 31, 44, 54, 55, 77, 93]
[17, 20, 26, 31, 44, 54, 55, 77, 93]
